# Generated by Django 4.0.5 on 2022-06-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.table')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cooked', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('billed', models.BooleanField(default=False)),
                ('dish_ID', models.IntegerField(default=-1)),
                ('extra_wishes', models.CharField(default=None, max_length=250)),
                ('table', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.waiter')),
            ],
        ),
    ]
