# Generated by Django 4.0.5 on 2022-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_billed_remove_order_cooked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='places',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='places',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
