# Generated by Django 4.0.5 on 2022-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_reservation_date_reservation_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_wishes',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
