# Generated by Django 4.0.5 on 2022-06-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_extra_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
