# Generated by Django 4.0.5 on 2022-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_reservation_table_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ManyToManyField(to='main.table'),
        ),
    ]
