# Generated by Django 4.0.5 on 2022-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_reservation_table_reservation_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dish_ID',
            new_name='dishId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='extra_wishes',
            new_name='extraWishes',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_name',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='table_number',
            new_name='tableNumber',
        ),
    ]
